# Generates mux's table of emoji from Unicode's emoji-test.txt: the
# fully-qualified ones, in Unicode's order, in their groups, with names.
import sys, re
src, out, version_line = sys.argv[1], sys.argv[2], ''
groups=[]  # (name, [(emoji, name)])
for line in open(src, encoding='utf-8'):
    line=line.rstrip('\n')
    if line.startswith('# Version:'):
        version_line=line[2:]
    m=re.match(r'# group: (.*)', line)
    if m:
        groups.append((m.group(1), [])); continue
    if not line or line.startswith('#'):
        continue
    codes, rest = line.split(';',1)
    status, comment = rest.split('#',1)
    if status.strip()!='fully-qualified':
        continue
    # comment: " 😀 E1.0 grinning face"
    parts=comment.strip().split(' ',2)
    glyph=''.join(chr(int(c,16)) for c in codes.split())
    name=parts[2] if len(parts)>2 else ''
    # A skin tone's variant: one of the five modifiers in it.
    toned=any(0x1F3FB <= int(c,16) <= 0x1F3FF for c in codes.split())
    if groups and groups[-1][0]!='Component':
        groups[-1][1].append((glyph, name, toned))
groups=[g for g in groups if g[0]!='Component' and g[1]]
# Every byte escaped: a hex escape takes all the hex digits after it, so
# no character is left plain beside one.
def lit(s): return '"' + ''.join('\\x%02x' % b for b in s.encode('utf-8')) + '"'
with open(out,'w',encoding='utf-8') as f:
    f.write('// SPDX-License-Identifier: AGPL-3.0-only\n')
    f.write('// Generated by tools/gen_emoji.py from Unicode\'s emoji-test.txt (%s): do not edit.\n' % version_line)
    f.write('// Every fully-qualified emoji, in Unicode\'s order, in its group, with its name.\n')
    f.write('export module mux.logic.emoji_list;\n\nimport std;\n\nexport namespace mux::logic {\n\n')
    f.write('struct emoji_entry {\n  std::string_view glyph;  // its UTF-8 bytes\n  std::string_view name;\n  bool toned = false;  // a skin tone\'s variant of another\n};\n')
    f.write('struct emoji_group {\n  std::string_view name;\n  std::span<const emoji_entry> entries;\n};\n\n')
    for gi,(g,items) in enumerate(groups):
        f.write('inline constexpr emoji_entry emoji_group_%d[] = {\n' % gi)
        for glyph,name,toned in items:
            f.write('    {%s, "%s", %s},\n' % (lit(glyph), name.replace('"','\\"'), 'true' if toned else 'false'))
        f.write('};\n')
    f.write('\ninline constexpr emoji_group emoji_groups[] = {\n')
    for gi,(g,items) in enumerate(groups):
        f.write('    {"%s", emoji_group_%d},\n' % (g, gi))
    f.write('};\n\n}  // namespace mux::logic\n')
print(len(groups), sum(len(i) for _,i in groups))
