# Resolved dependency inventory, collected after every subdirectory has asked
# the provider for its dependencies. No library is compiled by this step.
find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(mux_about_source "${CMAKE_CURRENT_SOURCE_DIR}")
set(mux_about_binary "${CMAKE_CURRENT_BINARY_DIR}")
target_include_directories(mux_modules PRIVATE "${mux_about_binary}/generated")
file(GLOB mux_about_license_files CONFIGURE_DEPENDS
    "${mux_about_source}/cmake/licenses/ffmpeg/COPYING.*")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${mux_about_source}/cmake/about.py" ${mux_about_license_files})
# A new commit or branch must refresh the identity even when no CMake file
# changed. git-path also handles linked worktrees.
foreach(ref HEAD HEAD_REF)
  if(ref STREQUAL HEAD_REF)
    execute_process(COMMAND git symbolic-ref -q HEAD WORKING_DIRECTORY "${mux_about_source}"
        OUTPUT_VARIABLE ref OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  endif()
  if(ref)
    execute_process(COMMAND git rev-parse --git-path "${ref}" WORKING_DIRECTORY "${mux_about_source}"
        OUTPUT_VARIABLE path OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(path)
      cmake_path(ABSOLUTE_PATH path BASE_DIRECTORY "${mux_about_source}" NORMALIZE)
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    endif()
  endif()
endforeach()
function(mux_about_quote out value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()
function(mux_about_metadata)
  get_property(ports GLOBAL PROPERTY CME_ASK_PORTS)
  get_property(dirs GLOBAL PROPERTY CME_ASK_DIRS)
  get_property(reached GLOBAL PROPERTY CME_LOCK_REACHED)
  list(APPEND ports ${reached})
  list(REMOVE_DUPLICATES ports)
  list(SORT ports)
  if(NOT ports)
    message(FATAL_ERROR "About dependency metadata requires CME_EXPORT_PORTS=ON")
  endif()
  get_property(asked GLOBAL PROPERTY CME_ASK_PORTS)
  get_property(primary_packages GLOBAL PROPERTY MUX_ABOUT_PRIMARY_PACKAGES)
  set(primary "")
  foreach(package IN LISTS primary_packages)
    get_property(port GLOBAL PROPERTY CME_PROVIDER_${package})
    if(port IN_LIST ports)
      list(APPEND primary "${port}")
    endif()
  endforeach()
  list(REMOVE_DUPLICATES primary)
  set(records "")
  foreach(port IN LISTS ports)
    get_property(tree GLOBAL PROPERTY CME_TREE_${port})
    set(deps "")
    if(tree)
      set(index 0)
      foreach(dir IN LISTS dirs)
        list(GET asked ${index} dep)
        math(EXPR index "${index} + 1")
        cmake_path(IS_PREFIX tree "${dir}" NORMALIZE inside)
        if(inside AND NOT dep STREQUAL port)
          list(APPEND deps "${dep}")
        endif()
      endforeach()
    endif()
    # Declared requirements also describe transitive dependencies of a
    # system package whose source wasn't configured here.
    set(requirements "")
    foreach(field DEPENDS DEPENDS_SYSTEM)
      cme_port_field(required "${port}" "${field}")
      list(APPEND requirements ${required})
    endforeach()
    cme_enabled_features("${port}" features)
    foreach(feature IN LISTS features)
      cme_feature_field(required "${port}" "${feature}" DEPENDS)
      list(APPEND requirements ${required})
    endforeach()
    foreach(spec IN LISTS requirements)
      cme_split_requirement("${spec}" package version required_features)
      get_property(dep GLOBAL PROPERTY CME_PROVIDER_${package})
      if(dep IN_LIST ports AND NOT dep STREQUAL port)
        list(APPEND deps "${dep}")
      endif()
    endforeach()
    list(REMOVE_DUPLICATES deps)
    list(SORT deps)
    set(dep_json "")
    foreach(dep IN LISTS deps)
      mux_about_quote(quoted "${dep}")
      string(APPEND dep_json "${quoted},")
    endforeach()
    string(REGEX REPLACE ",$" "" dep_json "${dep_json}")
    mux_about_quote(name "${port}")
    mux_about_quote(source "${tree}")
    set(is_primary false)
    if(port IN_LIST primary)
      set(is_primary true)
    endif()
    set(record "{\"name\":${name},\"source\":${source},\"primary\":${is_primary},\"dependencies\":[${dep_json}]")
    foreach(field LICENSE GITHUB_REPOSITORY GIT_REPOSITORY GIT_TAG URL IMPORT CARGO_PACKAGE CARGO_FEATURES CARGO_MANIFEST CARGO_NO_DEFAULT_FEATURES CARGO_TARGET)
      cme_port_field(value "${port}" "${field}")
      if(field STREQUAL CARGO_TARGET AND NOT value AND COMMAND cme_cargo_triple)
        cme_port_field(kind "${port}" IMPORT)
        if(kind STREQUAL cargo)
          cme_cargo_triple(value)
        endif()
      endif()
      mux_about_quote(quoted "${value}")
      string(APPEND record ",\"${field}\":${quoted}")
    endforeach()
    cme_port_field(provides "${port}" PROVIDES)
    set(actual "")
    foreach(package IN LISTS provides)
      get_property(found GLOBAL PROPERTY CME_PROVIDED_VERSION_${package})
      if(found MATCHES "^[0-9]+(\\.[0-9]+)*([-+~][A-Za-z0-9._+-]+)?$")
        set(actual "${found}")
        break()
      endif()
    endforeach()
    if(NOT actual AND tree)
      cme_effective_version("${port}" actual)
    endif()
    mux_about_quote(quoted "${actual}")
    string(APPEND records "${record},\"version\":${quoted}},")
  endforeach()
  string(REGEX REPLACE ",$" "" records "${records}")
  file(MAKE_DIRECTORY "${mux_about_binary}/generated")
  file(WRITE "${mux_about_binary}/generated/about-input.json" "[${records}]")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${mux_about_source}/cmake/about.py"
      --source "${mux_about_source}" --version "${PROJECT_VERSION}"
      --input "${mux_about_binary}/generated/about-input.json"
      --output "${mux_about_binary}/generated/about.inc"
      COMMAND_ERROR_IS_FATAL ANY)
endfunction()
cmake_language(DEFER CALL mux_about_metadata)
